/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:147
-- mogipix::moc::CellOrCellRangePSQL
CREATE TYPE CellOrCellRangePSQL AS ENUM (
	'CellPSQL',
	'CellRangePSQL'
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:224
-- mogipix::moc::CellSelectionPSQL
CREATE TYPE CellSelectionPSQL AS ENUM (
	'All',
	'Inside',
	'Border'
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:188
-- mogipix::bmoc::Statuspsql
CREATE TYPE Statuspsql AS ENUM (
	'In',
	'Out',
	'Unknown'
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:64
-- mogipix::bmoc::BMOCpsql
CREATE TYPE BMOCpsql;

-- src/bmoc.rs:64
-- mogipix::bmoc::bmocpsql_in
CREATE  FUNCTION "bmocpsql_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS BMOCpsql /* core::option::Option<mogipix::bmoc::BMOCpsql> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bmocpsql_in_wrapper';

-- src/bmoc.rs:64
-- mogipix::bmoc::bmocpsql_out
CREATE  FUNCTION "bmocpsql_out"(
	"input" BMOCpsql /* mogipix::bmoc::BMOCpsql */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bmocpsql_out_wrapper';

-- src/bmoc.rs:64
-- mogipix::bmoc::BMOCpsql
CREATE TYPE BMOCpsql (
	INTERNALLENGTH = variable,
	INPUT = bmocpsql_in, /* mogipix::bmoc::bmocpsql_in */
	OUTPUT = bmocpsql_out, /* mogipix::bmoc::bmocpsql_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:140
-- mogipix::moc::CellOrCellRangeMOCPSQL
CREATE TYPE CellOrCellRangeMOCPSQL;

-- src/moc.rs:140
-- mogipix::moc::cellorcellrangemocpsql_in
CREATE  FUNCTION "cellorcellrangemocpsql_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS CellOrCellRangeMOCPSQL /* core::option::Option<mogipix::moc::CellOrCellRangeMOCPSQL> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cellorcellrangemocpsql_in_wrapper';

-- src/moc.rs:140
-- mogipix::moc::cellorcellrangemocpsql_out
CREATE  FUNCTION "cellorcellrangemocpsql_out"(
	"input" CellOrCellRangeMOCPSQL /* mogipix::moc::CellOrCellRangeMOCPSQL */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cellorcellrangemocpsql_out_wrapper';

-- src/moc.rs:140
-- mogipix::moc::CellOrCellRangeMOCPSQL
CREATE TYPE CellOrCellRangeMOCPSQL (
	INTERNALLENGTH = variable,
	INPUT = cellorcellrangemocpsql_in, /* mogipix::moc::cellorcellrangemocpsql_in */
	OUTPUT = cellorcellrangemocpsql_out, /* mogipix::moc::cellorcellrangemocpsql_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:151
-- mogipix::moc::CellPSQL
CREATE TYPE CellPSQL;

-- src/moc.rs:151
-- mogipix::moc::cellpsql_in
CREATE  FUNCTION "cellpsql_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS CellPSQL /* core::option::Option<mogipix::moc::CellPSQL> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cellpsql_in_wrapper';

-- src/moc.rs:151
-- mogipix::moc::cellpsql_out
CREATE  FUNCTION "cellpsql_out"(
	"input" CellPSQL /* mogipix::moc::CellPSQL */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cellpsql_out_wrapper';

-- src/moc.rs:151
-- mogipix::moc::CellPSQL
CREATE TYPE CellPSQL (
	INTERNALLENGTH = variable,
	INPUT = cellpsql_in, /* mogipix::moc::cellpsql_in */
	OUTPUT = cellpsql_out, /* mogipix::moc::cellpsql_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:158
-- mogipix::moc::CellRangePSQL
CREATE TYPE CellRangePSQL;

-- src/moc.rs:158
-- mogipix::moc::cellrangepsql_in
CREATE  FUNCTION "cellrangepsql_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS CellRangePSQL /* core::option::Option<mogipix::moc::CellRangePSQL> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cellrangepsql_in_wrapper';

-- src/moc.rs:158
-- mogipix::moc::cellrangepsql_out
CREATE  FUNCTION "cellrangepsql_out"(
	"input" CellRangePSQL /* mogipix::moc::CellRangePSQL */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cellrangepsql_out_wrapper';

-- src/moc.rs:158
-- mogipix::moc::CellRangePSQL
CREATE TYPE CellRangePSQL (
	INTERNALLENGTH = variable,
	INPUT = cellrangepsql_in, /* mogipix::moc::cellrangepsql_in */
	OUTPUT = cellrangepsql_out, /* mogipix::moc::cellrangepsql_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:52
-- mogipix::Coo
CREATE TYPE Coo;

-- src/lib.rs:52
-- mogipix::coo_in
CREATE  FUNCTION "coo_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS Coo /* core::option::Option<mogipix::Coo> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'coo_in_wrapper';

-- src/lib.rs:52
-- mogipix::coo_out
CREATE  FUNCTION "coo_out"(
	"input" Coo /* mogipix::Coo */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'coo_out_wrapper';

-- src/lib.rs:52
-- mogipix::Coo
CREATE TYPE Coo (
	INTERNALLENGTH = variable,
	INPUT = coo_in, /* mogipix::coo_in */
	OUTPUT = coo_out, /* mogipix::coo_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:187
-- mogipix::MainWindMapPSQL
CREATE TYPE MainWindMapPSQL;

-- src/lib.rs:187
-- mogipix::mainwindmappsql_in
CREATE  FUNCTION "mainwindmappsql_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS MainWindMapPSQL /* core::option::Option<mogipix::MainWindMapPSQL> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mainwindmappsql_in_wrapper';

-- src/lib.rs:187
-- mogipix::mainwindmappsql_out
CREATE  FUNCTION "mainwindmappsql_out"(
	"input" MainWindMapPSQL /* mogipix::MainWindMapPSQL */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mainwindmappsql_out_wrapper';

-- src/lib.rs:187
-- mogipix::MainWindMapPSQL
CREATE TYPE MainWindMapPSQL (
	INTERNALLENGTH = variable,
	INPUT = mainwindmappsql_in, /* mogipix::mainwindmappsql_in */
	OUTPUT = mainwindmappsql_out, /* mogipix::mainwindmappsql_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:31
-- mogipix::moc::RangeMOCPSQL
CREATE TYPE RangeMOCPSQL;

-- src/moc.rs:31
-- mogipix::moc::rangemocpsql_in
CREATE  FUNCTION "rangemocpsql_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS RangeMOCPSQL /* core::option::Option<mogipix::moc::RangeMOCPSQL> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'rangemocpsql_in_wrapper';

-- src/moc.rs:31
-- mogipix::moc::rangemocpsql_out
CREATE  FUNCTION "rangemocpsql_out"(
	"input" RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'rangemocpsql_out_wrapper';

-- src/moc.rs:31
-- mogipix::moc::RangeMOCPSQL
CREATE TYPE RangeMOCPSQL (
	INTERNALLENGTH = variable,
	INPUT = rangemocpsql_in, /* mogipix::moc::rangemocpsql_in */
	OUTPUT = rangemocpsql_out, /* mogipix::moc::rangemocpsql_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:143
-- mogipix::UniqTuple
CREATE TYPE UniqTuple;

-- src/lib.rs:143
-- mogipix::uniqtuple_in
CREATE  FUNCTION "uniqtuple_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS UniqTuple /* core::option::Option<mogipix::UniqTuple> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'uniqtuple_in_wrapper';

-- src/lib.rs:143
-- mogipix::uniqtuple_out
CREATE  FUNCTION "uniqtuple_out"(
	"input" UniqTuple /* mogipix::UniqTuple */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'uniqtuple_out_wrapper';

-- src/lib.rs:143
-- mogipix::UniqTuple
CREATE TYPE UniqTuple (
	INTERNALLENGTH = variable,
	INPUT = uniqtuple_in, /* mogipix::uniqtuple_in */
	OUTPUT = uniqtuple_out, /* mogipix::uniqtuple_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:147
-- mogipix::bmoc::VertexPSQL
CREATE TYPE VertexPSQL;

-- src/bmoc.rs:147
-- mogipix::bmoc::vertexpsql_in
CREATE  FUNCTION "vertexpsql_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS VertexPSQL /* core::option::Option<mogipix::bmoc::VertexPSQL> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'vertexpsql_in_wrapper';

-- src/bmoc.rs:147
-- mogipix::bmoc::vertexpsql_out
CREATE  FUNCTION "vertexpsql_out"(
	"input" VertexPSQL /* mogipix::bmoc::VertexPSQL */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'vertexpsql_out_wrapper';

-- src/bmoc.rs:147
-- mogipix::bmoc::VertexPSQL
CREATE TYPE VertexPSQL (
	INTERNALLENGTH = variable,
	INPUT = vertexpsql_in, /* mogipix::bmoc::vertexpsql_in */
	OUTPUT = vertexpsql_out, /* mogipix::bmoc::vertexpsql_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:35
-- mogipix::mgx_best_starting_depth
CREATE  FUNCTION "mgx_best_starting_depth"(
	"d_max_deg" double precision /* f64 */
) RETURNS INT /* i32 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_best_starting_depth_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:242
-- mogipix::bmoc::mgx_bmoc_and
CREATE  FUNCTION "mgx_bmoc_and"(
	"bmoc" BMOCpsql, /* mogipix::bmoc::BMOCpsql */
	"other" BMOCpsql /* mogipix::bmoc::BMOCpsql */
) RETURNS BMOCpsql /* mogipix::bmoc::BMOCpsql */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_bmoc_and_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:174
-- mogipix::bmoc::mgx_bmoc_box_coverage
CREATE  FUNCTION "mgx_bmoc_box_coverage"(
	"depth" INT, /* i32 */
	"lon" double precision, /* f64 */
	"lat" double precision, /* f64 */
	"a" double precision, /* f64 */
	"b" double precision, /* f64 */
	"pa" double precision /* f64 */
) RETURNS BMOCpsql /* mogipix::bmoc::BMOCpsql */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_bmoc_box_coverage_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:129
-- mogipix::bmoc::mgx_bmoc_cone_coverage_approx
CREATE  FUNCTION "mgx_bmoc_cone_coverage_approx"(
	"depth" INT, /* i32 */
	"cone_lon" double precision, /* f64 */
	"cone_lat" double precision, /* f64 */
	"cone_radius" double precision /* f64 */
) RETURNS BMOCpsql /* mogipix::bmoc::BMOCpsql */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_bmoc_cone_coverage_approx_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:207
-- mogipix::bmoc::mgx_bmoc_contains
CREATE  FUNCTION "mgx_bmoc_contains"(
	"bmoc" BMOCpsql, /* mogipix::bmoc::BMOCpsql */
	"lon" double precision, /* f64 */
	"lat" double precision /* f64 */
) RETURNS Statuspsql /* mogipix::bmoc::Statuspsql */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_bmoc_contains_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:213
-- mogipix::bmoc::mgx_bmoc_contains_bool
CREATE  FUNCTION "mgx_bmoc_contains_bool"(
	"bmoc" BMOCpsql, /* mogipix::bmoc::BMOCpsql */
	"lon" double precision, /* f64 */
	"lat" double precision /* f64 */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_bmoc_contains_bool_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:135
-- mogipix::bmoc::mgx_bmoc_elliptical_cone_coverage
CREATE  FUNCTION "mgx_bmoc_elliptical_cone_coverage"(
	"depth" INT, /* i32 */
	"lon" double precision, /* f64 */
	"lat" double precision, /* f64 */
	"a" double precision, /* f64 */
	"b" double precision, /* f64 */
	"pa" double precision /* f64 */
) RETURNS BMOCpsql /* mogipix::bmoc::BMOCpsql */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_bmoc_elliptical_cone_coverage_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:328
-- mogipix::bmoc::mgx_bmoc_flag_one
CREATE  FUNCTION "mgx_bmoc_flag_one"(
	"bmoc" BMOCpsql /* mogipix::bmoc::BMOCpsql */
) RETURNS int8range[] /* alloc::vec::Vec<pgrx::datum::range::Range<i64>> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_bmoc_flag_one_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:318
-- mogipix::bmoc::mgx_bmoc_flag_zero
CREATE  FUNCTION "mgx_bmoc_flag_zero"(
	"bmoc" BMOCpsql /* mogipix::bmoc::BMOCpsql */
) RETURNS int8range[] /* alloc::vec::Vec<pgrx::datum::range::Range<i64>> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_bmoc_flag_zero_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:226
-- mogipix::bmoc::mgx_bmoc_not
CREATE  FUNCTION "mgx_bmoc_not"(
	"bmoc" BMOCpsql /* mogipix::bmoc::BMOCpsql */
) RETURNS BMOCpsql /* mogipix::bmoc::BMOCpsql */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_bmoc_not_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:265
-- mogipix::bmoc::mgx_bmoc_or
CREATE  FUNCTION "mgx_bmoc_or"(
	"bmoc" BMOCpsql, /* mogipix::bmoc::BMOCpsql */
	"other" BMOCpsql /* mogipix::bmoc::BMOCpsql */
) RETURNS BMOCpsql /* mogipix::bmoc::BMOCpsql */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_bmoc_or_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:258
-- mogipix::bmoc::mgx_bmoc_pg_and
CREATE  FUNCTION "mgx_bmoc_pg_and"(
	"bmoc" BMOCpsql, /* mogipix::bmoc::BMOCpsql */
	"other" BMOCpsql /* mogipix::bmoc::BMOCpsql */
) RETURNS BMOCpsql /* mogipix::bmoc::BMOCpsql */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_bmoc_pg_and_wrapper';

-- src/bmoc.rs:258
-- mogipix::bmoc::mgx_bmoc_pg_and
CREATE OPERATOR & (
	PROCEDURE="mgx_bmoc_pg_and",
	LEFTARG=BMOCpsql, /* mogipix::bmoc::BMOCpsql */
	RIGHTARG=BMOCpsql /* mogipix::bmoc::BMOCpsql */
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:163
-- mogipix::bmoc::mgx_bmoc_polygon_coverage
CREATE  FUNCTION "mgx_bmoc_polygon_coverage"(
	"depth" INT, /* i32 */
	"vertices" VertexPSQL[], /* alloc::vec::Vec<mogipix::bmoc::VertexPSQL> */
	"exact_solution" bool /* bool */
) RETURNS BMOCpsql /* mogipix::bmoc::BMOCpsql */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_bmoc_polygon_coverage_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:180
-- mogipix::bmoc::mgx_bmoc_ring_coverage_approx
CREATE  FUNCTION "mgx_bmoc_ring_coverage_approx"(
	"depth" INT, /* i32 */
	"cone_lon" double precision, /* f64 */
	"cone_lat" double precision, /* f64 */
	"cone_radius_int" double precision, /* f64 */
	"cone_radius_ext" double precision /* f64 */
) RETURNS BMOCpsql /* mogipix::bmoc::BMOCpsql */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_bmoc_ring_coverage_approx_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:339
-- mogipix::bmoc::mgx_bmoc_to_ranges
CREATE  FUNCTION "mgx_bmoc_to_ranges"(
	"bmoc" BMOCpsql /* mogipix::bmoc::BMOCpsql */
) RETURNS int8range[] /* alloc::vec::Vec<pgrx::datum::range::Range<i64>> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_bmoc_to_ranges_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:288
-- mogipix::bmoc::mgx_bmoc_xor
CREATE  FUNCTION "mgx_bmoc_xor"(
	"bmoc" BMOCpsql, /* mogipix::bmoc::BMOCpsql */
	"other" BMOCpsql /* mogipix::bmoc::BMOCpsql */
) RETURNS BMOCpsql /* mogipix::bmoc::BMOCpsql */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_bmoc_xor_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:141
-- mogipix::bmoc::mgx_bmoc_zone_coverage
CREATE  FUNCTION "mgx_bmoc_zone_coverage"(
	"depth" INT, /* i32 */
	"lon_min" double precision, /* f64 */
	"lat_min" double precision, /* f64 */
	"lon_max" double precision, /* f64 */
	"lat_max" double precision /* f64 */
) RETURNS BMOCpsql /* mogipix::bmoc::BMOCpsql */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_bmoc_zone_coverage_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:64
-- mogipix::mgx_center
CREATE  FUNCTION "mgx_center"(
	"depth" INT, /* i32 */
	"hash" bigint /* i64 */
) RETURNS Coo /* mogipix::Coo */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_center_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:117
-- mogipix::mgx_children
CREATE  FUNCTION "mgx_children"(
	"hash" bigint, /* i64 */
	"delta_depth" INT /* i32 */
) RETURNS int8range /* pgrx::datum::range::Range<i64> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_children_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:71
-- mogipix::bmoc::mgx_create_bmoc_psql
CREATE  FUNCTION "mgx_create_bmoc_psql"(
	"depth_max" INT, /* i32 */
	"entries" bigint[] /* alloc::vec::Vec<i64> */
) RETURNS BMOCpsql /* mogipix::bmoc::BMOCpsql */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_create_bmoc_psql_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:102
-- mogipix::moc::mgx_create_range_moc_psql
CREATE  FUNCTION "mgx_create_range_moc_psql"(
	"depth_max" INT, /* i32 */
	"ranges" int8range[] /* alloc::vec::Vec<pgrx::datum::range::Range<i64>> */
) RETURNS TEXT /* core::result::Result<alloc::string::String, pgrx::spi::SpiError> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_create_range_moc_psql_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:157
-- mogipix::bmoc::mgx_create_vertexpsql
CREATE  FUNCTION "mgx_create_vertexpsql"(
	"lon" double precision, /* f64 */
	"lat" double precision /* f64 */
) RETURNS VertexPSQL /* mogipix::bmoc::VertexPSQL */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_create_vertexpsql_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:171
-- mogipix::mgx_external_edge
CREATE  FUNCTION "mgx_external_edge"(
	"depth" INT, /* i32 */
	"hash" bigint, /* i64 */
	"delta_depth" INT /* i32 */
) RETURNS bigint[] /* alloc::vec::Vec<i64> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_external_edge_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:155
-- mogipix::mgx_from_uniq
CREATE  FUNCTION "mgx_from_uniq"(
	"uniq_hash" bigint /* i64 */
) RETURNS UniqTuple /* mogipix::UniqTuple */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_from_uniq_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:163
-- mogipix::mgx_from_zuniq
CREATE  FUNCTION "mgx_from_zuniq"(
	"zuniq" bigint /* i64 */
) RETURNS UniqTuple /* mogipix::UniqTuple */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_from_zuniq_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:19
-- mogipix::mgx_hash
CREATE  FUNCTION "mgx_hash"(
	"depth" INT, /* i32 */
	"lon" double precision, /* f64 */
	"lat" double precision /* f64 */
) RETURNS bigint /* i64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_hash_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:26
-- mogipix::mgx_hash_range
CREATE  FUNCTION "mgx_hash_range"(
	"depth" INT, /* i32 */
	"lon" double precision, /* f64 */
	"lat" double precision /* f64 */
) RETURNS int8range /* pgrx::datum::range::Range<i64> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_hash_range_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:179
-- mogipix::mgx_internal_edge
CREATE  FUNCTION "mgx_internal_edge"(
	"depth" INT, /* i32 */
	"hash" bigint, /* i64 */
	"delta_depth" INT /* i32 */
) RETURNS bigint[] /* alloc::vec::Vec<i64> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_internal_edge_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:215
-- mogipix::moc::mgx_is_in_moc
CREATE  FUNCTION "mgx_is_in_moc"(
	"moc" RangeMOCPSQL, /* mogipix::moc::RangeMOCPSQL */
	"lon" double precision, /* f64 */
	"lat" double precision /* f64 */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_is_in_moc_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:354
-- mogipix::moc::mgx_moc_and
CREATE  FUNCTION "mgx_moc_and"(
	"moc" RangeMOCPSQL, /* mogipix::moc::RangeMOCPSQL */
	"other" RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
) RETURNS RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_moc_and_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:336
-- mogipix::moc::mgx_moc_complement
CREATE  FUNCTION "mgx_moc_complement"(
	"moc" RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
) RETURNS RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_moc_complement_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:195
-- mogipix::moc::mgx_moc_degrade
CREATE  FUNCTION "mgx_moc_degrade"(
	"moc" RangeMOCPSQL, /* mogipix::moc::RangeMOCPSQL */
	"new_depth" INT /* i32 */
) RETURNS TEXT /* core::result::Result<alloc::string::String, pgrx::spi::SpiError> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_moc_degrade_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:205
-- mogipix::moc::mgx_moc_expanded
CREATE  FUNCTION "mgx_moc_expanded"(
	"moc" RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
) RETURNS TEXT /* core::result::Result<alloc::string::String, pgrx::spi::SpiError> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_moc_expanded_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:182
-- mogipix::moc::mgx_moc_from_ascii_ivoa
CREATE  FUNCTION "mgx_moc_from_ascii_ivoa"(
	"input" TEXT /* &str */
) RETURNS RangeMOCPSQL /* core::result::Result<mogipix::moc::RangeMOCPSQL, pgrx::spi::SpiError> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_moc_from_ascii_ivoa_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:293
-- mogipix::moc::mgx_moc_from_box
CREATE  FUNCTION "mgx_moc_from_box"(
	"lon" double precision, /* f64 */
	"lat" double precision, /* f64 */
	"a" double precision, /* f64 */
	"b" double precision, /* f64 */
	"pa" double precision, /* f64 */
	"depth" INT, /* i32 */
	"selection" CellSelectionPSQL /* mogipix::moc::CellSelectionPSQL */
) RETURNS TEXT /* core::result::Result<alloc::string::String, pgrx::spi::SpiError> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_moc_from_box_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:243
-- mogipix::moc::mgx_moc_from_cone
CREATE  FUNCTION "mgx_moc_from_cone"(
	"lon" double precision, /* f64 */
	"lat" double precision, /* f64 */
	"radius" double precision, /* f64 */
	"depth" INT, /* i32 */
	"delta_depth" INT, /* i32 */
	"selection" CellSelectionPSQL /* mogipix::moc::CellSelectionPSQL */
) RETURNS TEXT /* core::result::Result<alloc::string::String, pgrx::spi::SpiError> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_moc_from_cone_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:258
-- mogipix::moc::mgx_moc_from_elliptical_cone
CREATE  FUNCTION "mgx_moc_from_elliptical_cone"(
	"lon" double precision, /* f64 */
	"lat" double precision, /* f64 */
	"a" double precision, /* f64 */
	"b" double precision, /* f64 */
	"pa" double precision, /* f64 */
	"depth" INT, /* i32 */
	"delta_depth" INT, /* i32 */
	"selection" CellSelectionPSQL /* mogipix::moc::CellSelectionPSQL */
) RETURNS TEXT /* core::result::Result<alloc::string::String, pgrx::spi::SpiError> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_moc_from_elliptical_cone_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:275
-- mogipix::moc::mgx_moc_from_polygon
CREATE  FUNCTION "mgx_moc_from_polygon"(
	"vertices" VertexPSQL[], /* alloc::vec::Vec<mogipix::bmoc::VertexPSQL> */
	"complement" bool, /* bool */
	"depth" INT, /* i32 */
	"selection" CellSelectionPSQL /* mogipix::moc::CellSelectionPSQL */
) RETURNS TEXT /* core::result::Result<alloc::string::String, pgrx::spi::SpiError> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_moc_from_polygon_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:309
-- mogipix::moc::mgx_moc_from_ring
CREATE  FUNCTION "mgx_moc_from_ring"(
	"lon" double precision, /* f64 */
	"lat" double precision, /* f64 */
	"radius_int" double precision, /* f64 */
	"radius_ext" double precision, /* f64 */
	"depth" INT, /* i32 */
	"delta_depth" INT, /* i32 */
	"selection" CellSelectionPSQL /* mogipix::moc::CellSelectionPSQL */
) RETURNS TEXT /* core::result::Result<alloc::string::String, pgrx::spi::SpiError> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_moc_from_ring_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:362
-- mogipix::moc::mgx_moc_intersection
CREATE  FUNCTION "mgx_moc_intersection"(
	"moc" RangeMOCPSQL, /* mogipix::moc::RangeMOCPSQL */
	"other" RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
) RETURNS RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_moc_intersection_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:447
-- mogipix::moc::mgx_moc_minus
CREATE  FUNCTION "mgx_moc_minus"(
	"moc" RangeMOCPSQL, /* mogipix::moc::RangeMOCPSQL */
	"other" RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
) RETURNS RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_moc_minus_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:329
-- mogipix::moc::mgx_moc_not
CREATE  FUNCTION "mgx_moc_not"(
	"moc" RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
) RETURNS RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_moc_not_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:387
-- mogipix::moc::mgx_moc_or
CREATE  FUNCTION "mgx_moc_or"(
	"moc" RangeMOCPSQL, /* mogipix::moc::RangeMOCPSQL */
	"other" RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
) RETURNS RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_moc_or_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:127
-- mogipix::moc::mgx_moc_to_ascii
CREATE  FUNCTION "mgx_moc_to_ascii"(
	"moc" RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
) RETURNS TEXT /* core::result::Result<alloc::string::String, pgrx::spi::SpiError> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_moc_to_ascii_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:115
-- mogipix::moc::mgx_moc_to_ranges
CREATE  FUNCTION "mgx_moc_to_ranges"(
	"moc" RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
) RETURNS int8range[] /* alloc::vec::Vec<pgrx::datum::range::Range<i64>> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_moc_to_ranges_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:395
-- mogipix::moc::mgx_moc_union
CREATE  FUNCTION "mgx_moc_union"(
	"moc" RangeMOCPSQL, /* mogipix::moc::RangeMOCPSQL */
	"other" RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
) RETURNS RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_moc_union_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:420
-- mogipix::moc::mgx_moc_xor
CREATE  FUNCTION "mgx_moc_xor"(
	"moc" RangeMOCPSQL, /* mogipix::moc::RangeMOCPSQL */
	"other" RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
) RETURNS RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_moc_xor_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:202
-- mogipix::mgx_neighbours
CREATE  FUNCTION "mgx_neighbours"(
	"depth" INT, /* i32 */
	"hash" bigint, /* i64 */
	"include_center" bool /* bool */
) RETURNS MainWindMapPSQL /* mogipix::MainWindMapPSQL */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_neighbours_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:43
-- mogipix::mgx_nside
CREATE  FUNCTION "mgx_nside"(
	"depth" INT /* i32 */
) RETURNS INT /* i32 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_nside_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:73
-- mogipix::mgx_parent
CREATE  FUNCTION "mgx_parent"(
	"hash" bigint, /* i64 */
	"delta_depth" INT /* i32 */
) RETURNS bigint /* i64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_parent_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:281
-- mogipix::bmoc::mgx_pg_bmoc_or
CREATE  FUNCTION "mgx_pg_bmoc_or"(
	"bmoc" BMOCpsql, /* mogipix::bmoc::BMOCpsql */
	"other" BMOCpsql /* mogipix::bmoc::BMOCpsql */
) RETURNS BMOCpsql /* mogipix::bmoc::BMOCpsql */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_pg_bmoc_or_wrapper';

-- src/bmoc.rs:281
-- mogipix::bmoc::mgx_pg_bmoc_or
CREATE OPERATOR | (
	PROCEDURE="mgx_pg_bmoc_or",
	LEFTARG=BMOCpsql, /* mogipix::bmoc::BMOCpsql */
	RIGHTARG=BMOCpsql /* mogipix::bmoc::BMOCpsql */
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:304
-- mogipix::bmoc::mgx_pg_bmoc_xor
CREATE  FUNCTION "mgx_pg_bmoc_xor"(
	"bmoc" BMOCpsql, /* mogipix::bmoc::BMOCpsql */
	"other" BMOCpsql /* mogipix::bmoc::BMOCpsql */
) RETURNS BMOCpsql /* mogipix::bmoc::BMOCpsql */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_pg_bmoc_xor_wrapper';

-- src/bmoc.rs:304
-- mogipix::bmoc::mgx_pg_bmoc_xor
CREATE OPERATOR ^ (
	PROCEDURE="mgx_pg_bmoc_xor",
	LEFTARG=BMOCpsql, /* mogipix::bmoc::BMOCpsql */
	RIGHTARG=BMOCpsql /* mogipix::bmoc::BMOCpsql */
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:378
-- mogipix::moc::mgx_pg_moc_and
CREATE  FUNCTION "mgx_pg_moc_and"(
	"moc" RangeMOCPSQL, /* mogipix::moc::RangeMOCPSQL */
	"other" RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
) RETURNS RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_pg_moc_and_wrapper';

-- src/moc.rs:378
-- mogipix::moc::mgx_pg_moc_and
CREATE OPERATOR & (
	PROCEDURE="mgx_pg_moc_and",
	LEFTARG=RangeMOCPSQL, /* mogipix::moc::RangeMOCPSQL */
	RIGHTARG=RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:465
-- mogipix::moc::mgx_pg_moc_minus
CREATE  FUNCTION "mgx_pg_moc_minus"(
	"moc" RangeMOCPSQL, /* mogipix::moc::RangeMOCPSQL */
	"other" RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
) RETURNS RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_pg_moc_minus_wrapper';

-- src/moc.rs:465
-- mogipix::moc::mgx_pg_moc_minus
CREATE OPERATOR - (
	PROCEDURE="mgx_pg_moc_minus",
	LEFTARG=RangeMOCPSQL, /* mogipix::moc::RangeMOCPSQL */
	RIGHTARG=RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:411
-- mogipix::moc::mgx_pg_moc_or
CREATE  FUNCTION "mgx_pg_moc_or"(
	"moc" RangeMOCPSQL, /* mogipix::moc::RangeMOCPSQL */
	"other" RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
) RETURNS RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_pg_moc_or_wrapper';

-- src/moc.rs:411
-- mogipix::moc::mgx_pg_moc_or
CREATE OPERATOR | (
	PROCEDURE="mgx_pg_moc_or",
	LEFTARG=RangeMOCPSQL, /* mogipix::moc::RangeMOCPSQL */
	RIGHTARG=RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/moc.rs:438
-- mogipix::moc::mgx_pg_moc_xor
CREATE  FUNCTION "mgx_pg_moc_xor"(
	"moc" RangeMOCPSQL, /* mogipix::moc::RangeMOCPSQL */
	"other" RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
) RETURNS RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_pg_moc_xor_wrapper';

-- src/moc.rs:438
-- mogipix::moc::mgx_pg_moc_xor
CREATE OPERATOR ^ (
	PROCEDURE="mgx_pg_moc_xor",
	LEFTARG=RangeMOCPSQL, /* mogipix::moc::RangeMOCPSQL */
	RIGHTARG=RangeMOCPSQL /* mogipix::moc::RangeMOCPSQL */
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:420
-- mogipix::bmoc::mgx_polygon_characteristic_depth
CREATE  FUNCTION "mgx_polygon_characteristic_depth"(
	"vertices_deg" VertexPSQL[], /* alloc::vec::Vec<mogipix::bmoc::VertexPSQL> */
	"complement" bool /* bool */
) RETURNS INT /* i32 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_polygon_characteristic_depth_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:95
-- mogipix::mgx_siblings
CREATE  FUNCTION "mgx_siblings"(
	"depth" INT, /* i32 */
	"hash" bigint /* i64 */
) RETURNS int8range /* pgrx::datum::range::Range<i64> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_siblings_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:455
-- mogipix::bmoc::mgx_skyregion_box_contains
CREATE  FUNCTION "mgx_skyregion_box_contains"(
	"lon_deg" double precision, /* f64 */
	"lat_deg" double precision, /* f64 */
	"a_deg" double precision, /* f64 */
	"b_deg" double precision, /* f64 */
	"pa_deg" double precision, /* f64 */
	"test_lon_deg" double precision, /* f64 */
	"test_lat_deg" double precision /* f64 */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_skyregion_box_contains_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:358
-- mogipix::bmoc::mgx_skyregion_cone_contains
CREATE  FUNCTION "mgx_skyregion_cone_contains"(
	"lon_deg" double precision, /* f64 */
	"lat_deg" double precision, /* f64 */
	"radius_deg" double precision, /* f64 */
	"test_lon_deg" double precision, /* f64 */
	"test_lat_deg" double precision /* f64 */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_skyregion_cone_contains_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:377
-- mogipix::bmoc::mgx_skyregion_elliptical_cone_contains
CREATE  FUNCTION "mgx_skyregion_elliptical_cone_contains"(
	"lon_deg" double precision, /* f64 */
	"lat_deg" double precision, /* f64 */
	"a_deg" double precision, /* f64 */
	"b_deg" double precision, /* f64 */
	"pa_deg" double precision, /* f64 */
	"test_lon_deg" double precision, /* f64 */
	"test_lat_deg" double precision /* f64 */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_skyregion_elliptical_cone_contains_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:435
-- mogipix::bmoc::mgx_skyregion_polygon_contains
CREATE  FUNCTION "mgx_skyregion_polygon_contains"(
	"vertices_deg" VertexPSQL[], /* alloc::vec::Vec<mogipix::bmoc::VertexPSQL> */
	"complement" bool, /* bool */
	"test_lon_deg" double precision, /* f64 */
	"test_lat_deg" double precision /* f64 */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_skyregion_polygon_contains_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:477
-- mogipix::bmoc::mgx_skyregion_ring_contains
CREATE  FUNCTION "mgx_skyregion_ring_contains"(
	"lon_deg" double precision, /* f64 */
	"lat_deg" double precision, /* f64 */
	"r_min_deg" double precision, /* f64 */
	"r_max_deg" double precision, /* f64 */
	"test_lon_deg" double precision, /* f64 */
	"test_lat_deg" double precision /* f64 */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_skyregion_ring_contains_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/bmoc.rs:399
-- mogipix::bmoc::mgx_skyregion_zone_contains
CREATE  FUNCTION "mgx_skyregion_zone_contains"(
	"lon_min_deg" double precision, /* f64 */
	"lat_min_deg" double precision, /* f64 */
	"lon_max_deg" double precision, /* f64 */
	"lat_max_deg" double precision, /* f64 */
	"test_lon_deg" double precision, /* f64 */
	"test_lat_deg" double precision /* f64 */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_skyregion_zone_contains_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:125
-- mogipix::mgx_to_uniq
CREATE  FUNCTION "mgx_to_uniq"(
	"depth" INT, /* i32 */
	"hash" bigint /* i64 */
) RETURNS bigint /* i64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_to_uniq_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:134
-- mogipix::mgx_to_zuniq
CREATE  FUNCTION "mgx_to_zuniq"(
	"depth" INT, /* i32 */
	"hash" bigint /* i64 */
) RETURNS bigint /* i64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mgx_to_zuniq_wrapper';
/* </end connected objects> */

